### ISSUE TITLE
Bug: Broken View when integer field max value is 99999

### ISSUE THREAD

**Issue by coolcat-creations** [joomla-projects/custom-fields#120] opened 2016-06-14 18:54 UTC
i just created an example of each possible field 
and wanted to take a look at the form but the Userview is broken. Will add a screenshot later, not possible now due to connection issues.

**Comment by coolcat-creations** [comment] 2016-06-14 18:59
I tried to disable everything and enable it one by one and its the integer field. The setting is from 0 to 99999 step 1.

**Comment by laoneo** [comment] 2016-06-15 05:53
I can't reproduce the issue. Waiting for the screenshot.

**Comment by coolcat-creations** [comment] 2016-06-15 08:41
![bildschirmfoto 2016-06-15 um 09 41 31](https://cloud.githubusercontent.com/assets/828371/16073340/5dd303a6-32dd-11e6-9f2f-bdc6401df96f.png)
![bildschirmfoto 2016-06-15 um 09 40 56](https://cloud.githubusercontent.com/assets/828371/16073341/5dd6b050-32dd-11e6-8d1b-707fbbdc73a3.png)

**Comment by laoneo** [comment] 2016-06-15 09:09
Can you set error reporting to maximum in the Joomla configuration, is there an error shown?

**Comment by coolcat-creations** [comment] 2016-06-15 22:19
Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 80 bytes) in /Applications/MAMP/htdocs/customfields_contact/libraries/cms/html/select.php on line 495

**Comment by laoneo** [comment] 2016-06-16 05:48
How much memory does your server give a PHP process (You will find that information in the PHP Information tab in Joomla)? It is a server setup as there is not much to do here. The fields needs the amount memory to create the field.

**Comment by coolcat-creations** [comment] 2016-06-16 16:17
You mean memory limit ? It´s 128M

**Comment by laoneo** [comment] 2016-06-17 05:51
But that should be enough. Can you add the following XML code to the file administrator/components/com_content/models/forms/article.xml in the attribs section after line 152. The please open the article on the back end. Same error?

```
<field name="myintegervalue" type="integer" default="Some integer" label="Choose an integer" description="" first="1" last="99999" step="1" />
```

**Comment by coolcat-creations** [comment] 2016-06-17 13:49
Yes, same error then!

**Comment by laoneo** [comment] 2016-06-18 06:29
I'm closing this one as it is a bug in the Joomla CMS itself. Issue is opened here https://github.com/joomla/joomla-cms/issues/10861.

**Closed as completed by laoneo** 2016-06-18 06:29 UTC
Labels: awaiting fix elsewhere
