### ISSUE TITLE
Field Not Assigning Correctly

### ISSUE THREAD

**Issue by caseyzman** [joomla-projects/custom-fields#15] opened 2016-03-31 22:40 UTC
#### Steps to reproduce the issue

Standard Install from download
#### Expected result

Assigning Field to a Category, Field should only be visible if article is assigned to that category
#### Actual result

Field is visible on new article creation, regardless of category assignment
#### Additional comments

While it is nice to be able to assign a field to a specific Category, wouldn't it be just as logical to have the ability to assign the "Field Category" to a specific article-category. And on that note, the wording is a bit confusing, would "Field Set" or "Field Group" be better than "Field Categories".

**Comment by laoneo** [comment] 2016-04-01 07:26
Are you creating an article on the front or back end? When an article is created then it should load the fields of the default category.

Honestly I was also not happy with the name Field Categories, but categories are well known in Joomla and technically it is a category. SO I wanted to avoid to confuse people. Perhaps @brianteeman has an idea?

**Comment by caseyzman** [comment] 2016-04-01 18:47
Hello,
I am creating the article from the Admin Backend.

I have a test setup as:
Category: Laptops
Fields Category: Speed 
Fields: "RAM", "Processor", etc (assigned specifically to the Laptops Category only)

When I create a new article, the tab "Speed" is visible/available prior to selecting a category. Is this by design?

---

Also, I noticed while creating a new "Field Category" that the Breadcrumb at the top only says "Categories: Edit Categories", which actually confused me once, because I had forgotten if I was editing an actual "Category" or a "Field Category" (again misleading with the wording)

I know you mentioned that it technically "is a category", but, to the end user it really isn't a category (no category view), it is simply a collection/set of fields within a tab.

**Comment by b2z** [comment] 2016-04-12 06:42
I am agree that to avoid confusions between Joomla's Categories and Fields Categories we should choose a different name. I am for `Fields Group`.

**Comment by poproar** [comment] 2016-04-18 18:10
I was also confused at how each category is a tab in the categories option. I think there is some sort of recursion or I am confused because I am thinking about them like joomla categories. If I keep creating field categories and assign them a field they will have a tab and their seems to be something counter intuitive about that. I was trying to figure out how you could only assign fields for particular content categories. I understand the flexibility but I originally did not think field [groups] would also have custom fields, I am only associating them with articles or categories.

**Comment by brianteeman** [comment] 2016-04-18 18:12
A much better term would be groups as they are a group of fields

**Comment by laoneo** [comment] 2016-04-25 13:16
com_fields selects the first category in the list and shows the fields of it. To answer your question, yes, this is done by design. Because when you don't select a category, then the article will be assigned to the first one.

For the group name, can somebody open a pull request with the fixed language string? Thanks.

**Closed as completed by laoneo** 2016-04-25 13:16 UTC
