### ISSUE TITLE
Checkbox field shows wrong key

### ISSUE THREAD

**Issue by coolcat-creations** [joomla-projects/custom-fields#121] opened 2016-06-14 19:08 UTC
#### Steps to reproduce the issue

Create a checkbox field with Key yes and value 1, and Key No with value 0.
#### Expected result

The field should be displayed with two checkboxes Yes and No
#### Actual result

The field appears with two checkboxes 1 and No

**Comment by coolcat-creations** [comment] 2016-06-14 19:19
Same for the Radio Field.

**Comment by laoneo** [comment] 2016-06-15 06:33
Are you sure you want to have the keys and values like that and not the opposite? The problem is when the value is = or '' then it takes the key as representation. This is either a bug or feature in the formfield itself.

The radio field will not be available anymore when PR #104 is merged.

**Comment by coolcat-creations** [comment] 2016-06-15 08:39
But the value is 1 and 0, not empty
![bildschirmfoto 2016-06-15 um 09 38 45](https://cloud.githubusercontent.com/assets/828371/16073260/fb79250a-32dc-11e6-9839-ae0a7f2d29de.png)
![bildschirmfoto 2016-06-15 um 09 38 12](https://cloud.githubusercontent.com/assets/828371/16073261/fc15e85e-32dc-11e6-8379-f25c7b00891c.png)

From my side it´s a very usual key and value ?

**Comment by laoneo** [comment] 2016-06-15 09:08
In Joomla it is the opposite. Perhaps value is the wrong word. It is more of a label. If you flip the data, it should show correctly.

**Comment by coolcat-creations** [comment] 2016-06-15 09:25
Yes now it works. But that´s confusing as the key is stored in the database as value and the value is the "key" which is displayed to select from ?

![bildschirmfoto 2016-06-15 um 10 24 47](https://cloud.githubusercontent.com/assets/828371/16074671/808d2b00-32e3-11e6-8c24-fba329e66112.png)

**Comment by laoneo** [comment] 2016-06-15 11:14
What do you suggest for names then?

**Comment by coolcat-creations** [comment] 2016-06-15 22:11
Maybe Name and Value then?
For me key and value was logical until it was explained that it´s wrong :)

**Comment by laoneo** [comment] 2016-06-20 09:44
So "Key" becomes "Value" and "Value" becomes "Name"?

**Comment by coolcat-creations** [comment] 2016-06-20 15:43
Yes that would be good - and can we switch the positions? Name left and value right?

**Closed as completed** 2016-06-21 07:04 UTC
Labels: enhancement, ux
