### ISSUE TITLE
Image field dropdown shows JOPTION_DO_NOT_USE instead of -None Selected-

### ISSUE THREAD

**Issue by webchun** [joomla-projects/custom-fields#156] opened 2016-06-21 08:40 UTC
#### Steps to reproduce the issue

I have an image type custom field
I tried to edit article from the frontend
#### Expected result

The dropdown images should have -None Selected- in the first place
#### Actual result

The dropdown images have JOPTION_DO_NOT_USE in the first place
![images](http://i.imgur.com/HifIOy1.jpg?1)

**Comment by laoneo** [comment] 2016-06-21 11:11
Duplicate of #129.

**Closed as completed by laoneo** 2016-06-21 11:11 UTC
Labels: duplicate
