### ISSUE TITLE
Fields appear also as Fields in the Fieldgroup itself

### ISSUE THREAD

**Issue by coolcat-creations** [joomla-projects/custom-fields#125] opened 2016-06-14 21:21 UTC
Fields appear also as Fields in the Field Group itself.
i think thats not intended, is it?
![bildschirmfoto 2016-06-14 um 22 20 57](https://cloud.githubusercontent.com/assets/828371/16060165/5279ef7e-327e-11e6-9b69-f63d06940080.png)

**Comment by laoneo** [comment] 2016-06-15 06:44
This is a duplicate of #112.

**Closed as completed by laoneo** 2016-06-15 06:44 UTC
Labels: duplicate
