### ISSUE TITLE
Simplify rendering in overrides

### ISSUE THREAD

**Issue by coolcat-creations** [joomla-projects/custom-fields#102] opened 2016-06-01 21:25 UTC
I just managed to render the fields in the article view. For a non-developer quite a big step ;)
Now just an idea **(without having any clue!!!).**
It would be nice if it´s possible to render fields with commands like we do in the templates (jdoc)
like: `<jdoc:include type="field" name="aliasofthefield" style="overridestyleofthefield" />`

... i guess i have to run now ;-)

**Comment by laoneo** [comment] 2016-06-02 06:44
Congratulation!! Looks like we passed the end user test :smile: 

The problem is to render a field it always needs a context and an item (article in com_content). So your tag would need also a context attribute and an article id. But this can then not be done dynamically and different for every site.

**Comment by laoneo** [comment] 2016-06-02 09:21
Closing this as it is not doable.

**Closed as completed by laoneo** 2016-06-02 09:21 UTC
