### ISSUE TITLE
Menu link

### ISSUE THREAD

**Issue by brianteeman** [joomla-projects/custom-fields#65] opened 2016-04-05 10:24 UTC
Currently there is no menu link - you have to go to content and select something first

Should fields live in this menu or should it have its own link under components. Personally I would move it to the components menu as it is a setup thing not a content creation thing

**Comment by laoneo** [comment] 2016-04-05 11:01
There is also no menu link for com_categories. Using it as a horizontal component doesn't require a menu link. Can't see the benefit of having it's own menu item. I would leave it as it is. Looks more integrated.

**Comment by brianteeman** [comment] 2016-04-05 12:22
Yes there is a menu link for categories in the content menu

On 5 April 2016 at 12:01, Allon Moritz notifications@github.com wrote:

> There is also no menu link for com_categories. Using it as a horizontal
> component doesn't require a menu link. Can't see the benefit of having it's
> own menu item. I would leave it as it is. Looks more integrated.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/joomla-projects/custom-fields/issues/65#issuecomment-205756386

## 

Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by laoneo** [comment] 2016-04-05 12:47
No I understand it, I though you want to create a new menu entry under Components with the name _Fields_ where all custom fields are managed there.

**Comment by brianteeman** [comment] 2016-04-05 13:00
Well if Fields is for all components then yes i do

On 5 April 2016 at 13:47, Allon Moritz notifications@github.com wrote:

> No I understand it, I though you want to create a new menu entry under
> Components with the name _Fields_ where all custom fields are managed
> there.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/joomla-projects/custom-fields/issues/65#issuecomment-205783877

## 

Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by laoneo** [comment] 2016-04-22 07:15
Closing this as it is a duplicate of #73

**Closed as completed by laoneo** 2016-04-22 07:15 UTC
Labels: question
