### ISSUE TITLE
Feedback: What is the difference between Disable Field and Unpublish ?

### ISSUE THREAD

**Issue by coolcat-creations** [joomla-projects/custom-fields#92] opened 2016-05-28 18:13 UTC
I wonder what´s the difference between unpublishing a field and disabling it (options)

**Comment by brianteeman** [comment] 2016-05-30 10:27
tested with the editor field and "disabled" didnt seem to have any effect at all

**Comment by laoneo** [comment] 2016-05-31 06:29
If you unpublish a field, then it is not shown in the form at all. If you disable it, then it should show up on the form, but with disabled state.

**Comment by brianteeman** [comment] 2016-05-31 06:35
Thats what I thought but when I tried with an editor field there appeared
to be no effect
Also what is the difference between dsabled and readonly

On 31 May 2016 at 07:29, Allon Moritz notifications@github.com wrote:

> If you unpublish a field, then it is not shown in the form at all. If you
> disable it, then it should show up on the form, but with disabled state.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> https://github.com/joomla-projects/custom-fields/issues/92#issuecomment-222602910,
> or mute the thread
> https://github.com/notifications/unsubscribe/ABPH8cQklMEdvCH5Ar324J3NIcdItX3rks5qG9VRgaJpZM4IpIQh
> .

## 

Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by laoneo** [comment] 2016-05-31 07:05
Ok then it looks like a bug, Will have a look.

Difference between readonly and disabled is http://stackoverflow.com/questions/7730695/whats-the-difference-between-disabled-disabled-and-readonly-readonly-for-ht

**Comment by coolcat-creations** [comment] 2016-06-01 13:18
hmmm why would i use disabled and not unpublish it just? not clear for me :)

**Comment by laoneo** [comment] 2016-06-02 06:12
Unpublish is a state of the field which is visible on the back end. It is a Joomla thing. Disabled is a HTML state. It is also a property which is supported by JForm. Why people do disable fields can have various reasons. IMO they should have at least a choice to do it when they want.

**Comment by laoneo** [comment] 2016-06-04 09:00
@brianteeman It looks like another editor bug. At least when the field is disabled and you put in something into the editor field it doesn't get saved. Or how can I reproduce the issue you have?

**Comment by brianteeman** [comment] 2016-06-04 09:17
I didn't try to save anything I only tried to see if I could enter
somethjng.

**Comment by laoneo** [comment] 2016-06-04 10:30
Is it possible that you can open an issue on the CMS repo and reference this issue here as it looks like a bug or enhancement in the editor implementation? Thanks.

For the initial question. I would recommend to leave it as it is.

**Comment by laoneo** [comment] 2016-06-06 09:13
Can we agree to leave it as it is as the editor is now a simple text field?

**Comment by brianteeman** [comment] 2016-06-06 09:30
Arent you confusing the "description" field for a field and the wysiwyg
field type

On 6 June 2016 at 10:13, Allon Moritz notifications@github.com wrote:

> Can we agree to leave it as it is as the editor is now a simple text field?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/joomla-projects/custom-fields/issues/92#issuecomment-223906840,
> or mute the thread
> https://github.com/notifications/unsubscribe/ABPH8c2Joc1q3BGnMEC22ZqGstIM9G5Bks5qI-S5gaJpZM4IpIQh
> .

## 

Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by laoneo** [comment] 2016-06-06 09:33
> Arent you confusing the "description" field for a field and the wysiwyg
> field type

True.

**Comment by laoneo** [comment] 2016-06-09 06:59
I'm closing it as there are two functionalities meeting different use cases.

**Closed as completed by laoneo** 2016-06-09 06:59 UTC
Labels: ux
