### ISSUE TITLE
Slow (and useless) query

### ISSUE THREAD

**Issue by brianteeman** [joomla-projects/custom-fields#18] opened 2016-04-01 10:45 UTC
At 
administrator/index.php?option=com_fields&view=field&layout=edit&context=com_content.article

What is this query supposed to be doing

> SELECT *
>   FROM `n1dfs_content_types`
>   WHERE `type_alias` IN ('com_content.article.field')

I cant see it ever returning anything and in tests it often takes a very long time

**Comment by laoneo** [comment] 2016-04-01 11:31
This query don't come from com_fields, don't know who is doing it.

**Comment by wilsonge** [comment] 2016-04-01 20:30
comes from tags

**Comment by brianteeman** [comment] 2016-04-01 20:37
Needs fixing then as it is producing very slow queriues

On 1 April 2016 at 22:30, George Wilson notifications@github.com wrote:

> comes from tags
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/joomla-projects/custom-fields/issues/18#issuecomment-204557770

## 

Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by laoneo** [comment] 2016-05-03 09:09
I can't reproduce the issue with the latest code in this repo. Is it still valid? Or do I have to change a setting to reproduce it?

**Comment by wilsonge** [comment] 2016-05-03 09:51
This needs to go in the CMS Repo if it's still an issue. Close it here

**Closed as completed by wilsonge** 2016-05-03 09:51 UTC
Labels: awaiting fix elsewhere
